import { useEffect, useRef, useState } from "react";
import { Clipboard, Download, LoaderCircle, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { backendClient, isBackendConfigured, isPublicHttpUrl, type CandidateResult, type CreateJobRequest, type InspectResponse, type JobStatus } from "@/lib/url-backend";
import { LocalVideoPlugin } from "@/lib/local-video-plugin";
import { isNativeAndroid } from "@/lib/video-picker";
import { useI18n } from "@/i18n";

const time = (ms: number) => `${Math.floor(ms / 60000)}:${Math.floor(ms % 60000 / 1000).toString().padStart(2, "0")}`;
const bytes = (size?: number | null) => size == null ? "Unavailable" : `${(size / 1024 / 1024).toFixed(1)} MB`;
const terminal = new Set(["completed", "failed", "cancelled", "expired"]);

export function UrlWorkflow() {
  const { t, locale } = useI18n();
  const [url, setUrl] = useState(""); const [metadata, setMetadata] = useState<InspectResponse>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [options, setOptions] = useState<Omit<CreateJobRequest, "url">>({ durationMode: "auto", detectionMode: "balanced", outputQuality: "auto", layoutMode: "smart-crop", maximumCandidates: 5 });
  const [job, setJob] = useState<JobStatus>(); const [results, setResults] = useState<CandidateResult[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [downloads, setDownloads] = useState<Record<string, string>>({});
  const controller = useRef<AbortController | undefined>(undefined);
  useEffect(() => { const saved = sessionStorage.getItem("smartclip.urlJob"); if (saved && isBackendConfigured()) setJob({ jobId: saved, state: "queued", phase: "queued", createdAt: "", candidateCount: 0 }); return () => controller.current?.abort(); }, []);
  useEffect(() => {
    if (!job || terminal.has(job.state)) return; let stopped = false; controller.current?.abort(); const abort = new AbortController(); controller.current = abort; let attempts = 0;
    const poll = async () => { try { const next = await backendClient.status(job.jobId, abort.signal); if (stopped) return; setJob(next); attempts++; if (next.state === "completed") { const data = await backendClient.results(next.jobId); setResults(data.candidates); sessionStorage.removeItem("smartclip.urlJob"); return; } if (terminal.has(next.state)) { sessionStorage.removeItem("smartclip.urlJob"); return; } setTimeout(poll, attempts > 30 ? 5000 : 2000); } catch (reason) { if (!stopped) setError(reason instanceof Error ? reason.message : t("pollingFailed")); } };
    void poll(); return () => { stopped = true; abort.abort(); };
  // Polling is keyed only by identity; status updates must not create a second loop.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [job?.jobId]);
  const inspect = async () => { if (!isPublicHttpUrl(url)) { setError(t("invalidUrl")); return; } setBusy(true); setError(""); try { setMetadata(await backendClient.inspect(url)); } catch (reason) { setError(reason instanceof Error ? reason.message : t("inspectionFailed")); } finally { setBusy(false); } };
  const create = async () => { setBusy(true); setError(""); try { const created = await backendClient.createJob({ url, ...options }); sessionStorage.setItem("smartclip.urlJob", created.jobId); setResults([]); setJob({ ...created, state: created.state as JobStatus["state"], phase: created.state, candidateCount: 0 }); } catch (reason) { setError(reason instanceof Error ? reason.message : t("jobFailed")); } finally { setBusy(false); } };
  const cancel = async () => { if (job?.phase === "rendering" && !confirm(t("renderingConfirm"))) return; if (!job) return; controller.current?.abort(); try { setJob(await backendClient.cancel(job.jobId)); sessionStorage.removeItem("smartclip.urlJob"); } catch (reason) { setError(reason instanceof Error ? reason.message : t("genericError")); } };
  const download = async (candidate: CandidateResult) => { if (!job) return; setDownloads((v) => ({ ...v, [candidate.id]: "Downloading…" })); try { if (!isNativeAndroid()) throw new Error("Authenticated MediaStore downloads are available in the Android app."); const saved = await LocalVideoPlugin.downloadUrlVideo({ url: backendClient.fileUrl(job.jobId, candidate.filename), token: backendClient.getTokenForNativeDownload(), filename: candidate.filename }); setDownloads((v) => ({ ...v, [candidate.id]: `Saved ${saved.filename} (${bytes(saved.fileSize)}) to Movies/SmartClip` })); } catch (reason) { setDownloads((v) => ({ ...v, [candidate.id]: reason instanceof Error ? reason.message : t("downloadFailed") })); throw reason; } };
  const downloadSelected = async () => { for (const candidate of results.filter((item) => selected.has(item.id))) { try { await download(candidate); } catch { break; } } };
  if (!isBackendConfigured()) return <p role="alert" className="rounded-xl bg-amber-400/10 p-4 text-sm text-amber-200">{t("backendUnavailable")}</p>;
  return <div className="text-left">
    <h2 className="text-xl font-semibold">{t("processUrl")}</h2><p className="mt-1 text-sm text-muted-foreground">Processed through the private SmartClip server. Local videos are never uploaded.</p>
    {!metadata && !job && <><label className="mt-5 block text-sm">Video URL<input aria-label="Video URL" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3" value={url} onChange={(e) => setUrl(e.target.value)} /></label><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={async () => setUrl(await navigator.clipboard.readText())}><Clipboard size={16}/>{t("paste")}</Button><Button disabled={busy} onClick={inspect}>{busy ? <LoaderCircle className="animate-spin" size={16}/> : null}Inspect URL</Button><Button variant="outline" onClick={() => { setUrl(""); setError(""); }}>{t("clear")}</Button></div></>}
    {metadata && !job && <section className="mt-5 space-y-4"><div className="flex gap-4">{metadata.thumbnailUrl && <img src={metadata.thumbnailUrl} alt="Video thumbnail" className="h-24 w-36 rounded-lg object-cover"/>}<div><h3 className="font-semibold">{metadata.title}</h3><p className="text-sm text-muted-foreground">{metadata.uploader || "Uploader unavailable"} • {metadata.extractor || "Unknown platform"}</p><p className="text-sm">{metadata.duration ? time(metadata.duration * 1000) : "Duration unavailable"} • {metadata.sourceWidth && metadata.sourceHeight ? `${metadata.sourceWidth}×${metadata.sourceHeight}` : "Resolution unavailable"} • {bytes(metadata.estimatedFilesize)}</p><p className="text-sm">Quality: {metadata.qualityOptions.join(", ") || "Auto"} • Separate streams: {metadata.separateAudioVideo ? "Expected" : "No"}</p></div></div>{metadata.warnings.map((warning) => <p key={warning} className="text-xs text-amber-200">{warning}</p>)}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{([["Duration mode","durationMode",[["auto","Auto"],["30-plus","30 seconds or more"],["60-plus","60 seconds or more"]]],["Detection mode","detectionMode",[["conservative","Conservative"],["balanced","Balanced"],["aggressive","Aggressive"]]],["Output quality","outputQuality",[["auto","Auto"],["720p","720p"],["1080p","1080p"]]],["Layout mode","layoutMode",[["smart-crop","Smart Crop"],["fit-background","Fit Background"]]]] as const).map(([label,key,values]) => <label key={key} className="text-sm">{label}<select className="mt-1 w-full rounded-lg bg-black/30 p-2" value={options[key]} onChange={(e) => setOptions({...options,[key]:e.target.value})}>{values.map(([value,name]) => <option key={value} value={value}>{name}</option>)}</select></label>)}<label className="text-sm">Maximum candidates<input aria-label="Maximum candidates" type="number" min="1" max="5" className="mt-1 w-full rounded-lg bg-black/30 p-2" value={options.maximumCandidates} onChange={(e) => setOptions({...options,maximumCandidates: Math.max(1,Math.min(5,Number(e.target.value)))})}/></label></div><div className="flex gap-2"><Button onClick={create} disabled={busy}>{t("generateClips")}</Button><Button variant="outline" onClick={() => setMetadata(undefined)}>{t("back")}</Button></div></section>}
    {job && <section className="mt-5"><div className="flex items-center justify-between"><div><p className="font-semibold capitalize">{job.phase || job.state}</p><p className="text-sm text-muted-foreground">{job.message || (job.state === "queued" ? "Waking the private processing server. This may take up to a minute." : "Processing on the private server.")}</p></div>{!terminal.has(job.state) && <Button variant="outline" onClick={cancel}><X size={16}/>{t("cancelJob")}</Button>}</div>{job.progress != null ? <progress className="mt-3 w-full" value={job.progress} max="100"/> : !terminal.has(job.state) && <div className="mt-3 h-2 animate-pulse rounded bg-violet-500/50"/>}{job.state === "failed" && <p role="alert" className="mt-3 text-rose-300">{job.errorMessage || t("processingFailed")}</p>}{job.state === "cancelled" && <p className="mt-3">{t("jobCancelled")}</p>}{job.state === "expired" && <p className="mt-3">These temporary clips have expired. Generate them again.</p>}{terminal.has(job.state) && <Button className="mt-3" variant="outline" onClick={() => { setJob(undefined); setMetadata(undefined); setResults([]); }}>{t("startNewJob")}</Button>}</section>}
    {job?.state === "completed" && results.length === 0 && <p className="mt-4">{t("noHighlight")}</p>}
    {results.length > 0 && <section className="mt-5"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setSelected(new Set(results.map((r) => r.id)))}>{t("selectAll")}</Button><Button variant="outline" onClick={() => setSelected(new Set())}>{t("clearSelection")}</Button><Button disabled={!selected.size} onClick={downloadSelected}>{t("downloadSelected")}</Button></div><div className="mt-4 grid gap-3">{results.map((candidate,index) => <article key={candidate.id} className="rounded-xl border border-white/10 p-4"><label className="flex gap-2"><input type="checkbox" aria-label={t("selectCandidate", { current: index + 1 })} checked={selected.has(candidate.id)} onChange={() => setSelected((old) => { const next=new Set(old); if (next.has(candidate.id)) next.delete(candidate.id); else next.add(candidate.id); return next; })}/><strong>{t("candidate", { current: index + 1 })}</strong></label><p className="mt-2 text-sm">{time(candidate.startMs)}–{time(candidate.endMs)} • {time(candidate.durationMs)} • Score {candidate.score} • {candidate.confidence}</p><p className="text-sm text-muted-foreground">{candidate.reasons.join(" • ")}</p><p className="text-sm">{candidate.filename} • {candidate.resolution} • {bytes(candidate.size)} • Expires {new Date(candidate.expiresAt).toLocaleString(locale)}</p><Button className="mt-3" onClick={() => void download(candidate)}><Download size={16}/>{t("download")}</Button>{downloads[candidate.id] && <p className="mt-2 text-sm">{downloads[candidate.id]}</p>}</article>)}</div></section>}
    {error && <div role="alert" className="mt-4 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-300">{error}<Button className="ml-3" variant="outline" onClick={() => { setError(""); if (!metadata) void inspect(); }}>{t("retry")}</Button></div>}
  </div>;
}
