/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type LanguageMode = "id" | "en" | "system";
export type Locale = "id" | "en";
export const LANGUAGE_PREFERENCE_KEY = "smartclip.language";

const en = {
  home:"Home", projects:"Projects", downloads:"Downloads", settings:"Settings", language:"Language", indonesian:"Bahasa Indonesia", english:"English", followSystem:"Follow System",
  workspace:"SmartClip workspace", moreOptions:"More options", primaryNavigation:"Primary navigation", createClip:"CREATE A CLIP", homeDetail:"Turn long videos into focused short clips.", fromDevice:"From Device", pasteUrl:"Paste URL", localPrivate:"Private, processed locally", serverPrivate:"Processed through the private SmartClip server",
  chooseFile:"Choose a video file", selectVideo:"Select one local video", chooseVideo:"Choose Video", readingMetadata:"Reading metadata…", metadataReady:"Metadata ready", removeVideo:"Remove Video", fileSize:"File size", duration:"Duration", width:"Width", height:"Height", resolution:"Resolution", orientation:"Orientation", localUri:"Local URI",
  trimEditor:"Trim editor", reset:"Reset", source:"Source", start:"Start", end:"End", selected:"Selected", startTime:"Start time", endTime:"End time", first10:"First 10 seconds", seconds15:"15 seconds", seconds30:"30 seconds", fullDuration:"Full duration", exportClip:"Export Clip", cancel:"Cancel", workingLocally:"Working locally",
  automaticHighlights:"Automatic Highlights", exportVertical:"Export Vertical MP4", exportCompleted:"Export completed", filename:"Filename", savedTo:"Saved to", open:"Open", share:"Share", localStatus:"Local-first status", appVersion:"App version", platform:"Platform", videoAccess:"Video access", nativePicker:"Native system picker", browserFallback:"Browser fallback",
  recentActivity:"Recent activity", viewAll:"View all", noRecent:"No recent activity", noRecentDetail:"Choose a video or inspect a URL to begin.", draft:"Draft", localEditor:"Local editor", yourWorkspace:"Your workspace", projectsDetail:"Lightweight workflow history stored only on this device.", noProjects:"No projects yet", noProjectsDetail:"Videos you inspect or edit will appear here.", candidates:"candidates", clearHistory:"Clear history",
  saved:"Saved", deleteRecord:"Delete {name} record", downloadsDetail:"Exports and downloads created during known app sessions.", storageNotice:"Android storage remains private and permission-free. SmartClip does not request broad access to enumerate older gallery files.", nothingSaved:"Nothing saved yet", nothingSavedDetail:"Completed local exports and URL downloads will appear here.", personalize:"Personalize", settingsDetail:"Defaults are stored locally and never include your backend credential.",
  defaultDuration:"Default duration", defaultDetection:"Default detection", defaultQuality:"Default quality", auto:"Auto", conservative:"Conservative", balanced:"Balanced", aggressive:"Aggressive", recommended:"Recommended", privateServer:"Private server", privacy:"Privacy", storage:"Storage", about:"About", configured:"Configured", notConfigured:"Not configured", privacyDetail:"Device videos stay local. URL jobs use private temporary storage.", storageDetail:"Exports use scoped MediaStore; no broad storage permission.",
  processUrl:"Process a public video URL", videoUrl:"Video URL", paste:"Paste", inspectUrl:"Inspect URL", clear:"Clear", generateClips:"Generate Clips", back:"Back", selectAll:"Select All", clearSelection:"Clear Selection", downloadSelected:"Download Selected", download:"Download", retry:"Retry", candidate:"Candidate {current}", candidateCount:"{count} clip found", candidateCount_plural:"{count} clips found", processingCandidate:"Processing candidate {current} of {total}",
  invalidUrl:"Enter a valid public HTTP or HTTPS video URL.", inspectionFailed:"Inspection failed.", jobFailed:"Job creation failed.", pollingFailed:"Status polling failed.", downloadFailed:"Download failed.", processingFailed:"URL processing failed.", backendUnavailable:"URL processing is not configured for this build.", renderingConfirm:"Rendering has started. Cancel this job?", cancelJob:"Cancel Job", jobCancelled:"Job cancelled.", startNewJob:"Start New Job", noHighlight:"No strong highlight was found in this video.",
  unavailable:"Unavailable", uploaderUnavailable:"Uploader unavailable", unknownPlatform:"Unknown platform", durationUnavailable:"Duration unavailable", resolutionUnavailable:"Resolution unavailable", expected:"Expected", no:"No", maximumCandidates:"Maximum candidates", analyzeVideo:"Analyze Video", targetDuration:"Target duration", detectionMode:"Detection mode", exportSelected:"Export Selected", selectCandidate:"Select candidate {current}", failed:"Failed", cancelled:"Cancelled", completed:"Completed", preparing:"Preparing", rendering:"Rendering", saving:"Saving",
  genericError:"Something went wrong. Please try again.", permissionDenied:"Permission was not granted. Please allow access in the system picker.", selectionCancelled:"Video selection was cancelled. No file was changed.",
} as const;
export type TranslationKey = keyof typeof en;
const id: Record<TranslationKey,string> = { ...en,
  home:"Beranda", projects:"Proyek", downloads:"Unduhan", settings:"Pengaturan", language:"Bahasa", followSystem:"Ikuti bahasa sistem", workspace:"Ruang kerja SmartClip", moreOptions:"Opsi lainnya", primaryNavigation:"Navigasi utama", createClip:"BUAT KLIP", homeDetail:"Ubah video panjang menjadi klip pendek yang fokus.", fromDevice:"Dari Perangkat", pasteUrl:"Tempel URL", localPrivate:"Privat, diproses secara lokal", serverPrivate:"Diproses melalui server privat SmartClip",
  chooseFile:"Pilih file video", selectVideo:"Pilih satu video lokal", chooseVideo:"Pilih Video", readingMetadata:"Membaca metadata…", metadataReady:"Metadata siap", removeVideo:"Hapus Video", fileSize:"Ukuran file", duration:"Durasi", width:"Lebar", height:"Tinggi", resolution:"Resolusi", orientation:"Orientasi", localUri:"URI lokal", trimEditor:"Potong Manual", reset:"Atur Ulang", source:"Sumber", start:"Mulai", end:"Selesai", selected:"Dipilih", startTime:"Waktu mulai", endTime:"Waktu selesai", first10:"10 detik pertama", seconds15:"15 detik", seconds30:"30 detik", fullDuration:"Durasi penuh", exportClip:"Ekspor Klip", cancel:"Batal", workingLocally:"Diproses lokal",
  automaticHighlights:"Sorotan Otomatis", exportVertical:"Ekspor MP4 Vertikal", exportCompleted:"Ekspor selesai", filename:"Nama file", savedTo:"Disimpan ke", open:"Buka", share:"Bagikan", localStatus:"Status lokal", appVersion:"Versi aplikasi", videoAccess:"Akses video", nativePicker:"Pemilih sistem", browserFallback:"Browser", recentActivity:"Aktivitas terbaru", viewAll:"Lihat semua", noRecent:"Belum ada aktivitas", noRecentDetail:"Pilih video atau periksa URL untuk memulai.", draft:"Draf", localEditor:"Editor lokal",
  yourWorkspace:"Ruang kerja Anda", projectsDetail:"Riwayat alur kerja hanya disimpan di perangkat ini.", noProjects:"Belum ada proyek", noProjectsDetail:"Video yang diperiksa atau diedit akan muncul di sini.", candidates:"kandidat", clearHistory:"Hapus riwayat", saved:"Tersimpan", deleteRecord:"Hapus catatan {name}", downloadsDetail:"Ekspor dan unduhan dari sesi aplikasi ini.", storageNotice:"Penyimpanan Android tetap privat dan tanpa izin tambahan. SmartClip tidak meminta akses luas untuk membaca file galeri lama.", nothingSaved:"Belum ada yang tersimpan", nothingSavedDetail:"Ekspor lokal dan unduhan URL yang selesai akan muncul di sini.",
  personalize:"Sesuaikan", settingsDetail:"Setelan disimpan lokal dan tidak pernah memuat kredensial backend.", defaultDuration:"Durasi default", defaultDetection:"Deteksi default", defaultQuality:"Kualitas default", auto:"Otomatis", conservative:"Konservatif", balanced:"Seimbang", aggressive:"Agresif", recommended:"Disarankan", privateServer:"Server privat", privacy:"Privasi", storage:"Penyimpanan", about:"Tentang", configured:"Terkonfigurasi", notConfigured:"Belum dikonfigurasi", privacyDetail:"Video perangkat tetap lokal. Tugas URL memakai penyimpanan privat sementara.", storageDetail:"Ekspor memakai MediaStore terbatas; tanpa izin penyimpanan luas.",
  processUrl:"Proses URL video publik", videoUrl:"URL Video", paste:"Tempel", inspectUrl:"Periksa URL", clear:"Bersihkan", generateClips:"Buat Klip", back:"Kembali", selectAll:"Pilih Semua", clearSelection:"Hapus Pilihan", downloadSelected:"Unduh yang Dipilih", download:"Unduh", retry:"Coba Lagi", candidate:"Kandidat {current}", candidateCount:"{count} klip ditemukan", candidateCount_plural:"{count} klip ditemukan", processingCandidate:"Memproses kandidat {current} dari {total}", invalidUrl:"Masukkan URL video HTTP atau HTTPS publik yang valid.", inspectionFailed:"Gagal memeriksa URL.", jobFailed:"Gagal membuat tugas.", pollingFailed:"Gagal memeriksa status.", downloadFailed:"Unduhan gagal.", processingFailed:"Pemrosesan URL gagal.", backendUnavailable:"Pemrosesan URL belum dikonfigurasi untuk build ini.", renderingConfirm:"Rendering sudah dimulai. Batalkan tugas ini?", cancelJob:"Batalkan Tugas", jobCancelled:"Tugas dibatalkan.", startNewJob:"Mulai Tugas Baru", noHighlight:"Tidak ditemukan sorotan kuat dalam video ini.",
  unavailable:"Tidak tersedia", uploaderUnavailable:"Pengunggah tidak tersedia", unknownPlatform:"Platform tidak diketahui", durationUnavailable:"Durasi tidak tersedia", resolutionUnavailable:"Resolusi tidak tersedia", expected:"Ya", no:"Tidak", maximumCandidates:"Maksimum kandidat", analyzeVideo:"Analisis Video", targetDuration:"Durasi target", detectionMode:"Mode deteksi", exportSelected:"Ekspor yang Dipilih", selectCandidate:"Pilih kandidat {current}", failed:"Gagal", cancelled:"Dibatalkan", completed:"Selesai", preparing:"Menyiapkan", rendering:"Merender", saving:"Menyimpan", genericError:"Terjadi masalah. Coba lagi.", permissionDenied:"Izin tidak diberikan. Berikan akses melalui pemilih sistem.", selectionCancelled:"Pemilihan video dibatalkan. File tidak berubah.",
};
export const resolveLocale=(mode:LanguageMode,systemLocale=navigator.language):Locale=>mode==="system"?(/^id(?:-|$)/i.test(systemLocale)?"id":"en"):mode;
export const readLanguageMode=():LanguageMode=>{const value=localStorage.getItem(LANGUAGE_PREFERENCE_KEY);return value==="en"||value==="system"||value==="id"?value:"id"};
const interpolate=(value:string,vars:Record<string,string|number>={})=>value.replace(/\{(\w+)\}/g,(_,key:string)=>String(vars[key]??`{${key}}`));
export const translate=(locale:Locale,key:TranslationKey,vars?:Record<string,string|number>,count?:number)=>interpolate((locale==="id"?id:en)[count!==1&&`${key}_plural` in en?`${key}_plural` as TranslationKey:key],vars);
type Value={mode:LanguageMode;locale:Locale;setMode(mode:LanguageMode):void;t(key:TranslationKey,vars?:Record<string,string|number>,count?:number):string};
const Context=createContext<Value>({mode:"en",locale:"en",setMode:()=>undefined,t:(key,vars,count)=>translate("en",key,vars,count)});
export function I18nProvider({children,systemLocale}:{children:ReactNode;systemLocale?:string}){const[mode,setState]=useState<LanguageMode>(readLanguageMode);const locale=resolveLocale(mode,systemLocale??navigator.language);const value=useMemo<Value>(()=>({mode,locale,setMode(next){localStorage.setItem(LANGUAGE_PREFERENCE_KEY,next);setState(next)},t:(key,vars,count)=>translate(locale,key,vars,count)}),[mode,locale]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useI18n=()=>useContext(Context);
